"""Markdown rendering pipeline.

Assembles a multi-step pipeline to convert LLM-generated Markdown text
into safe HTML for WebView display. The pipeline handles:
  1. Math expression protection (delegates to math module)
  2. Tool result HTML protection
  3. List/table blank line normalization
  4. Blockquote code fence conversion
  5. Details tag fixup
  6. Python-Markdown rendering with extensions
  7. Restore protected content

Zero GTK dependency. Depends on math and cleanup modules.
"""

import re
import html
from typing import Optional, List, Tuple

from .math import _escape_math, _unescape_math, _fix_latex

# 代码高亮全局开关（由 set_code_highlight 控制）
_code_highlight_enabled = True


def set_code_highlight(enabled: bool):
    """设置是否启用 Pygments 代码语法高亮。"""
    global _code_highlight_enabled
    _code_highlight_enabled = enabled


def _get_markdown_extensions() -> List[str]:
    """根据当前设置构建 markdown 扩展列表。"""
    exts = [
        "fenced_code", "tables", "md_in_html", "def_list",
        "pymdownx.tilde",
        "pymdownx.caret",
        "pymdownx.mark",
    ]
    if _code_highlight_enabled:
        exts.append("codehilite")
    return exts

_markdown_lib = None
_markdown_initialized = False


def _get_markdown_lib():
    global _markdown_lib, _markdown_initialized
    if _markdown_initialized:
        return _markdown_lib
    try:
        import markdown
        try:
            import markdown.util
            block_elements = markdown.util.BLOCK_LEVEL_ELEMENTS
            if isinstance(block_elements, list):
                if 'details' not in block_elements:
                    block_elements.append('details')
                if 'summary' not in block_elements:
                    block_elements.append('summary')
            elif hasattr(block_elements, 'add'):
                block_elements.add('details')
                block_elements.add('summary')
        except Exception:
            pass
        _markdown_lib = markdown
    except ImportError:
        _markdown_lib = None
    _markdown_initialized = True
    return _markdown_lib


def _markdown_to_html_safe(text: str, fallback_content: Optional[str] = None) -> str:
    escaped_text, placeholders = _escape_math(text)
    placeholders = [_fix_latex(p) for p in placeholders]
    escaped_text, tool_placeholders = _escape_tool_results(escaped_text)
    escaped_text = _ensure_list_blankline(escaped_text)
    escaped_text = _ensure_table_blankline(escaped_text)
    escaped_text = _fix_blockquote_fences(escaped_text)
    escaped_text = _fix_details_blocks(escaped_text)

    md_lib = _get_markdown_lib()
    if md_lib is not None:
        html_text = md_lib.markdown(escaped_text, extensions=_get_markdown_extensions())
    else:
        if fallback_content is not None:
            html_text = fallback_content
        else:
            html_text = f"<pre><code>{escaped_text}</code></pre>"
    html_text = _unescape_tool_results(html_text, tool_placeholders)
    return _unescape_math(html_text, placeholders)


def _escape_tool_results(text: str) -> Tuple[str, List[str]]:
    """Scan the text for tool result box HTML chunks and escape them using placeholders."""
    placeholders = []

    def _repl(match):
        placeholder = f"\n<!--TOOL_RESULT_PLACEHOLDER_{len(placeholders)}-->"
        placeholders.append(match.group(1))
        return placeholder

_TOOL_RESULT_PATTERN1 = re.compile(r'(?:^|\n)(<div class="tool-result-box">.*?<!-- tool-result-marker -->)(?=\n|$)', re.DOTALL)
_TOOL_RESULT_PATTERN2 = re.compile(r'(?:^|\n)(<details class="tool-step-details".*?>.*?<!-- tool-step-marker -->)(?=\n|$)', re.DOTALL)
_TOOL_RESULT_PATTERN3 = re.compile(r'(?:^|\n)(<div class="tool-ask-user">.*?<!-- tool-step-marker -->)(?=\n|$)', re.DOTALL)


def _escape_tool_results(text: str) -> Tuple[str, List[str]]:
    """Scan the text for tool result box HTML chunks and escape them using placeholders."""
    placeholders = []

    def _repl(match):
        placeholder = f"\n<!--TOOL_RESULT_PLACEHOLDER_{len(placeholders)}-->"
        placeholders.append(match.group(1))
        return placeholder

    escaped_text = _TOOL_RESULT_PATTERN1.sub(_repl, text)
    escaped_text = _TOOL_RESULT_PATTERN2.sub(_repl, escaped_text)
    escaped_text = _TOOL_RESULT_PATTERN3.sub(_repl, escaped_text)
    return escaped_text, placeholders


def _unescape_tool_results(html_text: str, placeholders: List[str]) -> str:
    """Restore the escaped tool result box HTML chunks back to the final document."""
    for i, original in enumerate(placeholders):
        placeholder = f"<!--TOOL_RESULT_PLACEHOLDER_{i}-->"
        escaped_placeholder = f"&lt;!--TOOL_RESULT_PLACEHOLDER_{i}--&gt;"

        # Remove wrapping <p> tags generated by markdown for the placeholder comments
        p_pattern = re.compile(rf'<p>\s*({re.escape(placeholder)}|{re.escape(escaped_placeholder)})\s*</p>')
        html_text = p_pattern.sub(lambda m: original, html_text)

        html_text = html_text.replace(placeholder, original)
        html_text = html_text.replace(escaped_placeholder, original)
    return html_text


def _fix_blockquote_fences(text: str) -> str:
    """Convert blockquote sections containing code fences to raw HTML."""
    lines = text.split('\n')
    i = 0
    result = []
    in_code_block = False

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if stripped.startswith('```'):
            in_code_block = not in_code_block

        if not in_code_block and line.startswith('>'):
            bq_lines = []
            while i < len(lines) and lines[i].startswith('>'):
                bq_lines.append(lines[i])
                i += 1

            stripped_bq = []
            for bl in bq_lines:
                if bl.startswith('> '):
                    stripped_bq.append(bl[2:])
                elif bl == '>':
                    stripped_bq.append('')
                else:
                    stripped_bq.append(bl[1:])

            # Only convert if blockquote contains a code fence
            has_fence = any(s.lstrip().startswith('```') for s in stripped_bq)

            if has_fence:
                inner = '\n'.join(stripped_bq)
                result.append(f'\n<blockquote markdown="1">\n{inner}\n</blockquote>\n')
            else:
                result.extend(bq_lines)
        else:
            result.append(line)
            i += 1

    return '\n'.join(result)


def _fix_details_blocks(text: str) -> str:
    """Preprocess <details> tags to ensure markdown="1" attribute and proper blank line spacing.

    Without markdown="1", md_in_html extension skips parsing nested markdown inside details blocks.
    Without blank lines, tables/lists inside details blocks are squished and not recognized.
    """
    lines = text.split('\n')
    result = []
    i = 0
    in_code_block = False

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        stripped_lower = stripped.lower()

        if stripped.startswith('```'):
            in_code_block = not in_code_block

        if not in_code_block:
            # 1. Inject markdown="1" into details open tags if not present
            if stripped_lower.startswith('<details') and 'markdown' not in stripped_lower:
                line = re.sub(
                    r'<details(?![^>]*\bmarkdown\b)([^>]*)>',
                    r'<details\1 markdown="1">',
                    line,
                    flags=re.IGNORECASE
                )

            # 2. Insert blank line after summary block to allow nested markdown parsing
            if '</summary>' in stripped_lower:
                result.append(line)
                if i + 1 < len(lines):
                    next_stripped = lines[i + 1].strip()
                    if next_stripped and not next_stripped.startswith('</'):
                        result.append('')
                i += 1
                continue

            # 3. Insert blank line before details close tag to properly close nested tables
            if stripped_lower == '</details>':
                if result and result[-1].strip() and not result[-1].strip().startswith('<'):
                    result.append('')
                result.append(line)
                i += 1
                continue

        result.append(line)
        i += 1

    return '\n'.join(result)


def _ensure_list_blankline(text: str) -> str:
    """Ensure top-level lists are preceded by blank lines and normalize indent.

    Python markdown requires a blank line before <ul>/<ol> items.
    LLM output often omits these, causing list items to be rendered
    as plain text inside <p> tags (no line break before list).

    Also normalizes list item indentation to 4-space increments per
    nesting level. LLMs typically use 2 or 3 spaces per level, but
    Python markdown requires 4 spaces for proper nesting detection.

    Uses a stack of (orig_indent, norm_indent) tuples to track nesting
    levels: orig_indent is the original whitespace count from the source
    line, norm_indent is the normalized multiple-of-4 indent assigned
    to that level. Blank lines reset the stack.
    """
    lines = text.split('\n')
    result = []
    in_code_block = False
    list_stack = []
    for i, line in enumerate(lines):
        stripped = line.strip()

        if stripped.startswith('```'):
            in_code_block = not in_code_block

        if not in_code_block:
            is_list_item = bool(re.match(r'^[-*+]\s|^\d+[.)]\s', stripped))

            if is_list_item:
                orig_indent = len(line) - len(stripped)

                if i > 0 and not list_stack:
                    prev_line = lines[i - 1]
                    prev_stripped = prev_line.strip()
                    if prev_stripped:
                        result.append('')
                if not list_stack:
                    list_stack = [(orig_indent, 0)]
                    line = stripped
                elif orig_indent > list_stack[-1][0]:
                    new_indent = list_stack[-1][1] + 4
                    list_stack.append((orig_indent, new_indent))
                    line = ' ' * new_indent + stripped
                elif orig_indent == list_stack[-1][0]:
                    line = ' ' * list_stack[-1][1] + stripped
                else:
                    while list_stack and orig_indent < list_stack[-1][0]:
                        list_stack.pop()
                    if not list_stack:
                        list_stack = [(orig_indent, 0)]
                        line = stripped
                    elif orig_indent == list_stack[-1][0]:
                        line = ' ' * list_stack[-1][1] + stripped
                    else:
                        new_indent = list_stack[-1][1] + 4
                        list_stack.append((orig_indent, new_indent))
                        line = ' ' * new_indent + stripped
            elif not stripped:
                list_stack = []

        result.append(line)
    return '\n'.join(result)


_TABLE_SEPARATOR_RE = re.compile(r'^\s*\|[\s:\-|]+\|\s*$')


def _ensure_table_blankline(text: str) -> str:
    """Ensure pipe tables are surrounded by blank lines for Python-markdown's tables extension.

    覆盖三种边界（均在代码块外）：
    1. 表格前：普通文本/其他块紧跟表头时补空行（既有逻辑）；
    2. 表格后：表格行后紧跟普通文本/引用时补空行——否则 tables 扩展会把
       后续文本并进表格 tbody（如 "| 1 | 2 |\n总结文字" 中总结文字被吞）；
    3. 相邻表格：表1末行后紧跟表2表头（下一行是分隔行）时补空行——否则
       两个表格被解析为一个表格，分隔行变成普通行。
    """
    lines = text.split('\n')
    result = []
    in_code_block = False

    for i, line in enumerate(lines):
        stripped = line.strip()
        next_line = lines[i + 1].strip() if i + 1 < len(lines) else ''

        if stripped.startswith('```'):
            in_code_block = not in_code_block

        if not in_code_block and stripped:
            if stripped.startswith('|'):
                # ① 表格前补空行（前一行非空且非表格行）
                if (result and result[-1].strip()
                        and not result[-1].strip().startswith('|')):
                    result.append('')
                # ② 相邻表格：当前行是新表头（下一行是分隔行）且前一行是表格行
                elif (next_line and _TABLE_SEPARATOR_RE.match(next_line)
                      and result and result[-1].strip().startswith('|')):
                    result.append('')
            else:
                # ③ 表格后补空行：普通文本/引用紧跟表格行
                if result and result[-1].strip().startswith('|'):
                    result.append('')

        result.append(line)
    return '\n'.join(result)
